// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viralt.Infra.Context;

#nullable disable

namespace Viralt.Infra.Migrations
{
    [DbContext(typeof(ViraltContext))]
    [Migration("20260402225012_SweepWidgetPolish")]
    partial class SweepWidgetPolish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viralt.Domain.Models.Brand", b =>
                {
                    b.Property<long>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BrandId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("custom_domain");

                    b.Property<string>("LogoImage")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("logo_image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("primary_color");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("slug");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("BrandId")
                        .HasName("brands_pkey");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Campaign", b =>
                {
                    b.Property<long>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CampaignId"));

                    b.Property<string>("BgImage")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("bg_image");

                    b.Property<bool>("BlockVpn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("block_vpn");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<string>("CustomCss")
                        .HasColumnType("text")
                        .HasColumnName("custom_css");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EmailRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_required");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("EntryType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("entry_type");

                    b.Property<string>("FbPixelId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fb_pixel_id");

                    b.Property<string>("GaTrackingId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ga_tracking_id");

                    b.Property<string>("GeoCountries")
                        .HasColumnType("text")
                        .HasColumnName("geo_countries");

                    b.Property<string>("GtmId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("gtm_id");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("LogoImage")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("logo_image");

                    b.Property<int?>("MaxEntriesPerUser")
                        .HasColumnType("integer")
                        .HasColumnName("max_entries_per_user");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<int?>("MinEntry")
                        .HasColumnType("integer")
                        .HasColumnName("min_entry");

                    b.Property<bool>("NameRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("name_required");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<bool>("PhoneRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_required");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("redirect_url");

                    b.Property<bool>("RequireEmailVerification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("require_email_verification");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("TermsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("terms_url");

                    b.Property<string>("ThemeBgColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("theme_bg_color");

                    b.Property<string>("ThemeFont")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("theme_font");

                    b.Property<string>("ThemePrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("theme_primary_color");

                    b.Property<string>("ThemeSecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("theme_secondary_color");

                    b.Property<string>("TiktokPixelId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tiktok_pixel_id");

                    b.Property<string>("Timezone")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("title");

                    b.Property<string>("TopImage")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("top_image");

                    b.Property<long>("TotalEntries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_entries");

                    b.Property<long>("TotalParticipants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_participants");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("view_count");

                    b.Property<string>("WelcomeEmailBody")
                        .HasColumnType("text")
                        .HasColumnName("welcome_email_body");

                    b.Property<bool>("WelcomeEmailEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("welcome_email_enabled");

                    b.Property<string>("WelcomeEmailSubject")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("welcome_email_subject");

                    b.Property<int>("WinnerCount")
                        .HasColumnType("integer")
                        .HasColumnName("winner_count");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("youtube_url");

                    b.HasKey("CampaignId")
                        .HasName("campaigns_pkey");

                    b.HasIndex("BrandId");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntry", b =>
                {
                    b.Property<long>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EntryId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<bool>("Daily")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("daily");

                    b.Property<int>("Entries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("entries");

                    b.Property<string>("EntryLabel")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("entry_label");

                    b.Property<int>("EntryType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("entry_type");

                    b.Property<string>("EntryValue")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("entry_value");

                    b.Property<string>("ExternalEntryId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_entry_id");

                    b.Property<string>("ExternalProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_provider");

                    b.Property<string>("Icon")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("icon");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("instructions");

                    b.Property<bool>("Mandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mandatory");

                    b.Property<bool>("RequireVerification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("require_verification");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("EntryId")
                        .HasName("campaign_entries_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("campaign_entries", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntryOption", b =>
                {
                    b.Property<long>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("option_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OptionId"));

                    b.Property<long>("EntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("option_key");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("option_value");

                    b.HasKey("OptionId")
                        .HasName("campaign_entry_options_pkey");

                    b.HasIndex("EntryId");

                    b.ToTable("campaign_entry_options", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignField", b =>
                {
                    b.Property<long>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("field_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FieldId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<int>("FieldType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("field_type");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("required");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("FieldId")
                        .HasName("campaign_fields_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("campaign_fields", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignFieldOption", b =>
                {
                    b.Property<long>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("option_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OptionId"));

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_id");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("option_key");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("option_value");

                    b.HasKey("OptionId")
                        .HasName("campaign_field_options_pkey");

                    b.HasIndex("FieldId");

                    b.ToTable("campaign_field_options", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignView", b =>
                {
                    b.Property<long>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("view_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ViewId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referrer");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("ViewId")
                        .HasName("campaign_views_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("campaign_views", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Client", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClientId"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birthday");

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDisqualified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disqualified");

                    b.Property<bool>("IsWinner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_winner");

                    b.Property<string>("Name")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ReferralToken")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("referral_token");

                    b.Property<long?>("ReferredByClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("referred_by_client_id");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("token");

                    b.Property<int>("TotalEntries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_entries");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("ClientId")
                        .HasName("clients_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.ClientEntry", b =>
                {
                    b.Property<long>("EntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    b.Property<long>("ClientEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("client_entry_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClientEntryId"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("EntriesEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("entries_earned");

                    b.Property<string>("EntryValue")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("entry_value");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("VerificationData")
                        .HasColumnType("text")
                        .HasColumnName("verification_data");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verified");

                    b.HasKey("EntryId")
                        .HasName("client_entries_pkey");

                    b.HasIndex("ClientId");

                    b.ToTable("client_entries", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.ClientReward", b =>
                {
                    b.Property<long>("ClientRewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("client_reward_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClientRewardId"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<long>("RewardId")
                        .HasColumnType("bigint")
                        .HasColumnName("reward_id");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("unlocked_at");

                    b.HasKey("ClientRewardId")
                        .HasName("client_rewards_pkey");

                    b.HasIndex("ClientId");

                    b.HasIndex("RewardId");

                    b.ToTable("client_rewards", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Prize", b =>
                {
                    b.Property<long>("PrizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("prize_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PrizeId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("coupon_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("image");

                    b.Property<int?>("MinEntriesRequired")
                        .HasColumnType("integer")
                        .HasColumnName("min_entries_required");

                    b.Property<int>("PrizeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("prize_type");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("title");

                    b.HasKey("PrizeId")
                        .HasName("prizes_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("prizes", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Referral", b =>
                {
                    b.Property<long>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("referral_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReferralId"));

                    b.Property<int>("BonusEntriesAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("bonus_entries_awarded");

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ReferredClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("referred_client_id");

                    b.Property<long>("ReferrerClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("referrer_client_id");

                    b.HasKey("ReferralId")
                        .HasName("referrals_pkey");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ReferredClientId");

                    b.HasIndex("ReferrerClientId");

                    b.ToTable("referrals", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Submission", b =>
                {
                    b.Property<long>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("submission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SubmissionId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caption");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("file_url");

                    b.Property<decimal?>("JudgeScore")
                        .HasColumnType("numeric")
                        .HasColumnName("judge_score");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("VoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vote_count");

                    b.HasKey("SubmissionId")
                        .HasName("submissions_pkey");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ClientId");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.UnlockReward", b =>
                {
                    b.Property<long>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reward_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RewardId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EntriesThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("entries_threshold");

                    b.Property<string>("Image")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("image");

                    b.Property<int>("RewardType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("reward_type");

                    b.Property<string>("RewardValue")
                        .HasColumnType("text")
                        .HasColumnName("reward_value");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("title");

                    b.HasKey("RewardId")
                        .HasName("unlock_rewards_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("unlock_rewards", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Vote", b =>
                {
                    b.Property<long>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("vote_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VoteId"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("voted_at");

                    b.HasKey("VoteId")
                        .HasName("votes_pkey");

                    b.HasIndex("SubmissionId");

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Webhook", b =>
                {
                    b.Property<long>("WebhookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("webhook_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WebhookId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Events")
                        .HasColumnType("text")
                        .HasColumnName("events");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("secret");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("WebhookId")
                        .HasName("webhooks_pkey");

                    b.ToTable("webhooks", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Winner", b =>
                {
                    b.Property<long>("WinnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("winner_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WinnerId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ClaimData")
                        .HasColumnType("text")
                        .HasColumnName("claim_data");

                    b.Property<bool>("Claimed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("claimed");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<bool>("Notified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notified");

                    b.Property<long?>("PrizeId")
                        .HasColumnType("bigint")
                        .HasColumnName("prize_id");

                    b.Property<DateTime>("SelectedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("selected_at");

                    b.Property<int>("SelectionMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("selection_method");

                    b.HasKey("WinnerId")
                        .HasName("winners_pkey");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PrizeId");

                    b.ToTable("winners", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Campaign", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Brand", "Brand")
                        .WithMany("Campaigns")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("fk_brand_campaign");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntry", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("CampaignEntries")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_entry");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntryOption", b =>
                {
                    b.HasOne("Viralt.Domain.Models.CampaignEntry", "Entry")
                        .WithMany("CampaignEntryOptions")
                        .HasForeignKey("EntryId")
                        .IsRequired()
                        .HasConstraintName("fk_entry_options");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignField", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("CampaignFields")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_field");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignFieldOption", b =>
                {
                    b.HasOne("Viralt.Domain.Models.CampaignField", "Field")
                        .WithMany("CampaignFieldOptions")
                        .HasForeignKey("FieldId")
                        .IsRequired()
                        .HasConstraintName("fk_field_options");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignView", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("CampaignViews")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_view");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Client", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("Clients")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_clients");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Viralt.Domain.Models.ClientEntry", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Client", "Client")
                        .WithMany("ClientEntries")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_client_entry_client");

                    b.HasOne("Viralt.Domain.Models.CampaignEntry", "Entry")
                        .WithOne("ClientEntry")
                        .HasForeignKey("Viralt.Domain.Models.ClientEntry", "EntryId")
                        .IsRequired()
                        .HasConstraintName("fk_client_entry_entry");

                    b.Navigation("Client");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Viralt.Domain.Models.ClientReward", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Client", "Client")
                        .WithMany("ClientRewards")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_client_reward");

                    b.HasOne("Viralt.Domain.Models.UnlockReward", "Reward")
                        .WithMany("ClientRewards")
                        .HasForeignKey("RewardId")
                        .IsRequired()
                        .HasConstraintName("fk_reward_client_reward");

                    b.Navigation("Client");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Prize", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("Prizes")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_prize");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Referral", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_referral");

                    b.HasOne("Viralt.Domain.Models.Client", "ReferredClient")
                        .WithMany()
                        .HasForeignKey("ReferredClientId")
                        .IsRequired()
                        .HasConstraintName("fk_referred_client");

                    b.HasOne("Viralt.Domain.Models.Client", "ReferrerClient")
                        .WithMany()
                        .HasForeignKey("ReferrerClientId")
                        .IsRequired()
                        .HasConstraintName("fk_referrer_client");

                    b.Navigation("Campaign");

                    b.Navigation("ReferredClient");

                    b.Navigation("ReferrerClient");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Submission", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("Submissions")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_submission");

                    b.HasOne("Viralt.Domain.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_client_submission");

                    b.Navigation("Campaign");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Viralt.Domain.Models.UnlockReward", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("UnlockRewards")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_reward");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Vote", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Submission", "Submission")
                        .WithMany("Votes")
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("fk_submission_vote");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Winner", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("Winners")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_winner");

                    b.HasOne("Viralt.Domain.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_client_winner");

                    b.HasOne("Viralt.Domain.Models.Prize", "Prize")
                        .WithMany("Winners")
                        .HasForeignKey("PrizeId")
                        .HasConstraintName("fk_prize_winner");

                    b.Navigation("Campaign");

                    b.Navigation("Client");

                    b.Navigation("Prize");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Brand", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Campaign", b =>
                {
                    b.Navigation("CampaignEntries");

                    b.Navigation("CampaignFields");

                    b.Navigation("CampaignViews");

                    b.Navigation("Clients");

                    b.Navigation("Prizes");

                    b.Navigation("Submissions");

                    b.Navigation("UnlockRewards");

                    b.Navigation("Winners");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntry", b =>
                {
                    b.Navigation("CampaignEntryOptions");

                    b.Navigation("ClientEntry");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignField", b =>
                {
                    b.Navigation("CampaignFieldOptions");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Client", b =>
                {
                    b.Navigation("ClientEntries");

                    b.Navigation("ClientRewards");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Prize", b =>
                {
                    b.Navigation("Winners");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Submission", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Viralt.Domain.Models.UnlockReward", b =>
                {
                    b.Navigation("ClientRewards");
                });
#pragma warning restore 612, 618
        }
    }
}
