// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viralt.Infra.Context;

#nullable disable

namespace Viralt.Infra.Migrations
{
    [DbContext(typeof(ViraltContext))]
    partial class ViraltContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viralt.Domain.Models.Campaign", b =>
                {
                    b.Property<long>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CampaignId"));

                    b.Property<string>("BgImage")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("bg_image");

                    b.Property<string>("CustomCss")
                        .HasColumnType("text")
                        .HasColumnName("custom_css");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EmailRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_required");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<int?>("MinEntry")
                        .HasColumnType("integer")
                        .HasColumnName("min_entry");

                    b.Property<bool>("NameRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("name_required");

                    b.Property<bool>("PhoneRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_required");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("title");

                    b.Property<string>("TopImage")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("top_image");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("youtube_url");

                    b.HasKey("CampaignId")
                        .HasName("campaigns_pkey");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntry", b =>
                {
                    b.Property<long>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EntryId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<bool>("Daily")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("daily");

                    b.Property<int>("Entries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("entries");

                    b.Property<string>("EntryLabel")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("entry_label");

                    b.Property<int>("EntryType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("entry_type");

                    b.Property<string>("EntryValue")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("entry_value");

                    b.Property<bool>("Mandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mandatory");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("EntryId")
                        .HasName("campaign_entries_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("campaign_entries", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntryOption", b =>
                {
                    b.Property<long>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("option_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OptionId"));

                    b.Property<long>("EntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("option_key");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("option_value");

                    b.HasKey("OptionId")
                        .HasName("campaign_entry_options_pkey");

                    b.HasIndex("EntryId");

                    b.ToTable("campaign_entry_options", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignField", b =>
                {
                    b.Property<long>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("field_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FieldId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<int>("FieldType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("field_type");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("required");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("FieldId")
                        .HasName("campaign_fields_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("campaign_fields", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignFieldOption", b =>
                {
                    b.Property<long>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("option_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OptionId"));

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_id");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("option_key");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("option_value");

                    b.HasKey("OptionId")
                        .HasName("campaign_field_options_pkey");

                    b.HasIndex("FieldId");

                    b.ToTable("campaign_field_options", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.Client", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClientId"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birthday");

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("token");

                    b.HasKey("ClientId")
                        .HasName("clients_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.ClientEntry", b =>
                {
                    b.Property<long>("EntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    b.Property<long>("ClientEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("client_entry_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClientEntryId"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("EntryValue")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("entry_value");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("EntryId")
                        .HasName("client_entries_pkey");

                    b.HasIndex("ClientId");

                    b.ToTable("client_entries", (string)null);
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntry", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("CampaignEntries")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_entry");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntryOption", b =>
                {
                    b.HasOne("Viralt.Domain.Models.CampaignEntry", "Entry")
                        .WithMany("CampaignEntryOptions")
                        .HasForeignKey("EntryId")
                        .IsRequired()
                        .HasConstraintName("fk_entry_options");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignField", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("CampaignFields")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_field");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignFieldOption", b =>
                {
                    b.HasOne("Viralt.Domain.Models.CampaignField", "Field")
                        .WithMany("CampaignFieldOptions")
                        .HasForeignKey("FieldId")
                        .IsRequired()
                        .HasConstraintName("fk_field_options");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Client", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Campaign", "Campaign")
                        .WithMany("Clients")
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_clients");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Viralt.Domain.Models.ClientEntry", b =>
                {
                    b.HasOne("Viralt.Domain.Models.Client", "Client")
                        .WithMany("ClientEntries")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_client_entry_client");

                    b.HasOne("Viralt.Domain.Models.CampaignEntry", "Entry")
                        .WithOne("ClientEntry")
                        .HasForeignKey("Viralt.Domain.Models.ClientEntry", "EntryId")
                        .IsRequired()
                        .HasConstraintName("fk_client_entry_entry");

                    b.Navigation("Client");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Campaign", b =>
                {
                    b.Navigation("CampaignEntries");

                    b.Navigation("CampaignFields");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignEntry", b =>
                {
                    b.Navigation("CampaignEntryOptions");

                    b.Navigation("ClientEntry");
                });

            modelBuilder.Entity("Viralt.Domain.Models.CampaignField", b =>
                {
                    b.Navigation("CampaignFieldOptions");
                });

            modelBuilder.Entity("Viralt.Domain.Models.Client", b =>
                {
                    b.Navigation("ClientEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
